---
title: "DO #1g stan incremental analysis"
author:
- name: Robert Sellers
  affiliation: The Jackson Laboratory
date: "`r paste('Last knit on:',format(Sys.time(), '%d %B %Y'))`"
abstract: |
latex_engine: pdflatex
output:
  html_document:
    fig_caption: yes
    force_captions: yes
    number_sections: true
    theme: lumen
    toc: yes
    toc_float: yes
    df_print: paged
    # code_folding: "hide"
  pdf_document:
    fig_caption: yes
    force_captions: yes
    highlight: pyments
    keep_tex: yes
    latex_engine: xelatex
    number_sections: no
    toc: no
    
---
```{r}
library(rstan)
library(tidyverse)

# contains harmony plate collection class builder
source("scripts/harmony_utils.R")
# various add-on scripts and stats tools
source("scripts/custom_tools.R")
# standrc code that actually works
source('scripts/standrc_evals.R')
# point to parent data directory
setwd("data/invitro/")
selected_dir <- "./do_focus_merge_2"
# Warning - this currently expects a temp_files data dir 
# Set overwrite to TRUE when underlying data dir has been changed
harmony_collection <- harmony_create_collection(dir = selected_dir, overwrite = FALSE)

# env
options(scipen = 999) # suppress sci notation
```

```{r}
# function for https://benchmarkdose.org/
# garbage
benchmark_save <- function(data){
  data <- data %>%
    group_by(individual_id) %>%
    sample_n_groups(7) %>%
    mutate(individual_id = cur_group_id()-1) %>%
    arrange(dose,individual_id,response)
  # benchmark_save(feature_subset)
  data$dose[data$dose == 0] <- 0.001

  write.table(data.frame("Dose" = data$dose, "Individual" = data$individual_id, "Response" = as.integer(data$response)), "~/Desktop/example.tsv",sep = '\t', row.names = F,quote = FALSE)
}
#benchmark_save(feature_subset)
```
- https://discourse.mc-stan.org/t/fitting-a-non-linear-growth-model-with-stan/4246
- https://www.magesblog.com/post/2015-11-03-loss-developments-via-growth-curves-and/


```{r}
plot_posterior_growth_ci <- function(fit, dat, cred = TRUE){
  browser()
  Y_mean <- rstan::extract(fit, "Y_mean")
  Y_mean_mean <- apply(Y_mean$Y_mean, 2, mean)
  Y_pred <- rstan::extract(fit, "Y_pred")
  Y_pred_mean <- apply(Y_pred$Y_pred, 2, mean)
  
  if (cred){
    Y_mean_cred <- apply(Y_mean$Y_mean, 2, quantile, c(0.05, 0.95))
    Y_pred_cred <- apply(Y_pred$Y_pred, 2, quantile, c(0.05, 0.95))
    plot(dat$y ~ dat$x, xlab="x", ylab="Y", 
       ylim=c(-1, 101), main="Non-linear Growth Curve")
    lines(dat$x, Y_mean_mean)
    points(dat$x, Y_pred_mean, pch=19)
    lines(dat$x, Y_mean_cred[1,], col=4)
    lines(dat$x, Y_mean_cred[2,], col=4)
    lines(dat$x, Y_pred_cred[1,], col=2)
    lines(dat$x, Y_pred_cred[2,], col=2)
    legend(x="bottomright", bty="n", lwd=2, lty=c(NA, NA, 1, 1,1),
           legend=c("observation", "prediction", "mean prediction",
                    "90% mean cred. interval", "90% pred. cred. interval"),
           col=c(1,1,1,4,2),  pch=c(1, 19, NA, NA, NA))
  }else{
    plot(dat$y ~ dat$x, xlab="x", ylab="Y", 
       ylim=c(-1, 101), main="Non-linear Growth Curve")
    lines(dat$x, Y_mean_mean)
    points(dat$x, Y_pred_mean, pch=19)
    legend(x="bottomright", bty="n", lwd=2, lty=c(NA, NA, 1, 1,1),
           legend=c("observation", "prediction", "mean prediction"),
           col=c(1,1,1,4,2),  pch=c(1, 19, NA, NA, NA))
  }
}

build_standrc_object_single <- function(stan_dat, stancode, fit){
  out <- list()
  out$data <- stan_dat
  out$model <- stancode
  out$stan <- fit
  out$fixedpars <- c("slope","lasy","uasy","ed")
  out$pars <- c("pslope", "plasy", "puasy", "ped", "passym")
  out$curves <- list(pars=c(FALSE,FALSE,FALSE,FALSE),
                     J=1,
                     names=NULL
                     )
  out$fixed <- c(NA,NA,NA,NA,0)
  out$fct <- LL.4()
  class(out) <- "standrc"
  return(out)
}
```

Model 1: y = a with a > 0

Model 2: y = a exp(x/b) with a > 0

Model 3: y = a exp(±(x/b)d) with a > 0, b > 0, d ≥ 1

Model 4: y = a [c – (c – 1) exp(−x/b)] with a > 0, b > 0, c > 0

Model 5: y = a [c – (c – 1) exp(−(x/b)d)] with a > 0, b > 0, c > 0, d ≥ 1 where y is any

### Original growth model

```{r}
feature_subset <- harmony_collection$all_plates %>%
  group_by(dir) %>%
  mutate(dir_id = cur_group_id()) %>%
  group_by(individual) %>%
  mutate(individual_id = cur_group_id())


feature_subset <- prepare_data_for_stan('infocus_nucleus_hoechst_ser_dark_1px_mean',
                                        feature_subset, 
                                        log_ = FALSE)


# feature_subset_2 <- arrange(feature_subset, dose)   %>%
#   group_by(individual_id) %>%
#   select(individual_id, response, dose, mouse) %>% 
#   rename(y = response, x = dose) 

# slope_test <- feature_subset_2 %>% 
#   group_by(individual_id) %>% 
#   nest() %>% 
#   mutate(model = map(data, ~ lm(Y ~ 1 + x, data = .x) %>% tidy)) %>% 
#   unnest(model) %>% 
#   filter(term == 'x')

dat <- list(
  "N" = 7498,  
  "x" = feature_subset$dose,
  "y" = feature_subset$response,
  "pb" = 0,
  "pc" = 100,
  "pd" = 0.01,
  "pe" = 0.75,
  "pf" = 0)

stan_ll4 <- "
data {
  int<lower=0> N; 
  real y[N];
  real<lower=0> x[N];
  real pb; 
  real pc; 
  real pd; 
  real pe;
} 
parameters { 
  real<lower=0> sigmasq_y;
  real slope; 
  real lasy; 
  real uasy; 
  real<lower=0> ed;
} 
transformed parameters {
  real<lower=0> sigma_y;
  real mu[N];
  sigma_y = sqrt(sigmasq_y); 
  for(i in 1:N){ 
    mu[i] = lasy  + ( uasy - lasy ) / (1 + exp(-exp( slope ) * (log(x[i]/ ed ))))^exp( 0 );
  }
} 
model {
  slope ~ normal(pb, 100) ; 
  lasy ~ normal(pc, 100) ; 
  uasy ~ normal(pd, 100) ; 
  ed ~ normal(pe, 100) ;
  sigmasq_y ~ inv_gamma(0.001, 0.001) ; 
  y ~ normal(mu, sigma_y);
}
generated quantities {
  real Y_mean[N]; 
  real Y_pred[N]; 
  real residuals[N];
  real log_lik[N];
  real pslope; 
  real plasy; 
  real puasy; 
  real ped; 
  real passym;
  for (i in 1:N){
    residuals[i] = y[i] - mu[i];
    log_lik[i] = normal_log(y[i], mu[i], sigma_y);
    Y_mean[i] = lasy  + ( uasy - lasy ) / (1 + exp(-exp( slope ) * (log(x[i]/ ed ))))^exp( 0 );
    Y_pred[i] = normal_rng(Y_mean[i], sigma_y);   
  }
  pslope  =  slope  ; 
  plasy = lasy  ; 
  puasy  =  uasy  ; 
  ped  =  ed  ; 
  passym  =  0  ;
}
"

stan_dat <- readRDS("~/Desktop/example.RDS")
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
fit_ll4 <- rstan::stan(model_code = stan_ll4, 
            model_name = "new", 
            data = stan_dat)

# baseline model
#print(fit, c("alpha", "beta", "lambda", "sigma"))
#traceplot(fit, pars=c("a","b","lambda","sigma_y"))
# trankplot(fit, pars=c("a","b","lambda","tau", "sigma"))
#precis(fit, pars=c("a","b","lambda","tau", "sigma_y"))
#plot_posterior_growth_ci(fit,dat, cred=TRUE)
```
# parameter fits
## 1 parameter

 https://academic.oup.com/toxsci/article/66/2/298/1734199

```{r}
# baseline model
#print(fit, c("alpha", "beta", "lambda", "sigma"))
traceplot(fit_ll4, pars=c("slope","lasy","uasy", "ed","sigmasq_y"))
rethinking::trankplot(fit_ll4, pars=c("slope","lasy","uasy", "ed","sigmasq_y"))
rethinking::precis(fit_ll4, pars=c("slope","lasy","uasy", "ed","sigmasq_y"))
# tempdf <- data.frame("x" = stan_dat$x, "y" = stan_dat$y)[order(stan_dat$y),][order(stan_dat$x),]
# stan_dat$x <- tempdf$x
# stan_dat$y <- tempdf$y
#stan_dat_for_plot <- vector2[order(vector1, decreasing=TRUE)]
standrc_obj <- build_standrc_object_single(stan_dat, stan_ll4, fit_ll4)
plot_stan <- ggplot_build(plot(standrc_obj))

plot_new(standrc_obj)
plot_posterior_growth_ci(fit_ll4, stan_dat)
```
