---
title: "Founders #3 Dose-response extraction"
author:
- name: Robert Sellers
  affiliation: The Jackson Laboratory
date: "`r paste('Last knit on:',format(Sys.time(), '%d %B %Y'))`"
abstract: |
latex_engine: pdflatex
output:
  html_document:
    fig_caption: yes
    force_captions: yes
    number_sections: true
    theme: lumen
    toc: yes
    toc_float: yes
    df_print: paged
    # code_folding: "hide"
  pdf_document:
    fig_caption: yes
    force_captions: yes
    highlight: pyments
    keep_tex: yes
    latex_engine: xelatex
    number_sections: no
    toc: no
    
---

# Programming environment

```{r message=FALSE}
# various add-on scripts and stats tools
source("scripts/custom_tools.R")

library(tidyverse)
library(drc) # dose response library
library(nlme) # mixed effects library
library(medrc) # drc + medrc wrapper
library(ggplot2) 
library(ggpubr) # ggplot extension
library(foreach)
library(doSNOW)
library(microbenchmark)
```

# Load data

## Load processed RDS / plate_collection data from temp_files

```{r warning=FALSE, echo = FALSE}
# point to parent data directory
setwd("temp_files/")
temp_data_storage <- "founders_quantal_reduced.RData"
founders_quantal_collection <- readRDS(temp_data_storage)
```


# DRC extraction

```{r}
response_transform <- function(response_var){
    skew_val <- e1071::skewness(response_var)
    skew.score <- function(c, x) (e1071::skewness(log(x + c)))^2
    if (!is.na(skew_val)){
      print(paste0("performing log transformation with skew:", skew_val))
      best.c <- stats::optimise(skew.score, c(0, 1), x = response_var)$minimum
      response_var <- log(response_var + best.c)
    }else{
      print("No optimization")
      # to be continued
      #df$response <- log(df$response)
    }
    return(response_var)
}

mixed_drc_plot_v2 <- function(x, var, logx=TRUE) {
  # data prep

  level = NULL
  ranef = TRUE
  ndose = 100
  fct <- x$fct
  yname <- as.character(x$form)[2]
  xname <- as.character(x$form)[3]
  if (is.null(x$curveid)) {
    pform <- x$form
  } else {
    fname <- as.character(x$curveid)[3]
    pform <- paste(yname, "~", xname, "+", fname)
  }
  mf <- model.frame(pform, data = x$data)
  if (logx == TRUE) {
    if (min(mf[, 2]) == 0) {
      m0 <- mean(unique(mf[, 2])[order(unique(mf[, 2]))][1:2])
    } else {
      m0 <- min(mf[, 2])
    }
    dr <- exp(seq(log(m0), log(max(mf[, 2])), length = ndose))
    mf[mf[, 2] == 0, 2] <- m0
  } else {
    dr <- seq(min(mf[, 2]), max(mf[, 2]), length = ndose)
  }
  cf <- coef(x$fit)
  predictions <-
    stack(data.frame(apply(cf, 1, function(para)
      x$fct$fct(dr, rbind(
        para
      )))))$values
  pdat <-
    data.frame(
      predictions,
      dose = rep(dr, times = nrow(cf)),
      ID = rep(rownames(cf), each = ndose)
    )
  # hack
  effect_split <-
    data.frame(matrix(
      unlist(strsplit(pdat$ID, "/")),
      nrow = length(strsplit(pdat$ID, "/")),
      byrow = TRUE
    ))
  names(effect_split) <- c("mouse", "strain", "plate")
  # get more data
  pdat2 <- cbind(pdat, effect_split)
  mf2 <- cbind(mf, x$data[, c("sex", "strain", "mouse")])
  # set up shapes
  #point_shapes <- c(95,95)
  point_shapes <- c("-", "-")
  point_color <- c("blue", "red")
  names(point_shapes) <- c("M", "F")
  names(point_color) <- c("M", "F")
  ccol_lut <- setNames(
    c(
      "#FFDC00" ,
      "#888888" ,
      "#F08080" ,
      "#0064C9" ,
      "#7FDBFF" ,
      "#2ECC40",
      "#FF4136",
      "#B10DC9"
    ),
    c("AJ", "B6", "129", "NOD", "NZO", "CAST", "PWK", "WSB")
  )
  find_groups <- x$fit$groups  %>%
    tidyr::separate(mouse, c("cc", "repl"))
  find_groups <-
    merge(find_groups,
          data.frame(ccol_lut),
          by.x = "cc",
          by.y = "row.names")
  color_map <-
    setNames(find_groups$ccol_lut, as.character(find_groups$plate))
  cmap <- color_map[!duplicated(names(color_map))]
  
  sex_nudge <- function(sex) {
    if (sex == 'M') {
      return (-50)
    } else{
      return(50)
    }
  }
  
  #mf2$dose <- as.factor(mf2$dose)
  p1 <- ggplot() +
    theme(
      panel.grid.minor = element_line(colour = "white", size = 0.5),
      panel.grid.major.x = element_line(color = "black", size = 0.25),
      legend.position = "none",
      plot.title = element_text(
        size = 6,
        hjust = 1,
        vjust = 0.5,
        face = 'bold'
      ),
      axis.title = element_text(size = 6, face = "italic"),
      axis.text.x = element_text(size = 6),
      axis.text.y = element_text(size = 6)
    )  +
    # ggrepel::geom_text_repel(aes(x=dose, y=predictions,label = strain),
    #            data = pdat2 %>% filter(dose == max(dose)),
    #            nudge_x = 3,
    #            size = 2)+
    geom_line(aes(
      x = pdat2$dose,
      y = pdat2$predictions,
      color = pdat2$ID
    )) +
    geom_point(
      data = mf2,
      aes(
        x = dose,
        y = response,
        group = factor(sex),
        #position = dodge, #sex_nudge(sex),
        color = as.factor(sex),
        shape = as.factor(sex),
        size = 2
      ),
      na.rm = TRUE,
      position = position_dodge(width = 0.4),
      show.legend = FALSE
    ) +
    #coord_trans(x='log') +
    
    #scale_x_discrete(name ="Dose (ppm)",limits = unique(mf2$dose), labels=c("0.05" = "0")) +
    scale_shape_manual(values = point_shapes) +
    scale_color_manual(values = c(cmap, point_color)) +
    scale_x_discrete(
      name = "Dose (ppm)",
      limits = unique(mf2$dose),
      breaks = c(as.numeric(mf2$dose)),
      labels = c(as.character(as.numeric(mf2$dose)))
    ) +
    labs(
      title = paste0("Feature: ", var, "\nFunction: ", x$fct$text),
      x = "Dose (ppm)",
      y = var
    )
  return(p1)
}



try_mixed_drm_v3 <- function(data, 
                          response_var, 
                          transform, 
                          weight_var = 'dose',
                          fct,
                          strain_name){
  
  # prepare data
  data <- data %>%
    stats::na.omit() %>% 
    dplyr::mutate(sex = as.factor(sex),
          dose = as.numeric(as.character(dose))) %>%
    dplyr::select_(.dots = 
                     list(response = response_var, 
                          weight_var = weight_var,
                          dose = 'dose', 
                          plate = 'plate', 
                          sex = 'sex', 
                          strain = 'strain',
                          mouse = 'mouse')
                   )

  if ('zero_replace' %in% transform){
    print("replacing zero with 0.0001")
    data$response[data$response == 0] <- 0.0001
  }
   if ('log_skew_transform' %in% transform) {
    data$response <- log_skew_transform(data$response)
  } 
    if ('scale_positive' %in% transform){
    # rescale data between 0 and 1
    new_max = abs(min(data$response))+0.001
    print(paste("scaling to 0 and",new_max))
    data$response <- scales::rescale(data$response,to = c(0,new_max),finite=TRUE,na.rm=TRUE)
    } 
  
  # curve specific difference to the parameter average
  check_plate <- medrc::metadrm(
    response ~ dose,
    data = data,
    fct = fct,
    ind = plate,
    struct = "UN"
  )
  
  cmat <- matrix(coefficients(check_plate), ncol=4)
  # fixed effect starting values
  m <- apply(cmat, 2, mean)
  names(m) <- letters[2:5]
  rmat <- t(apply(cmat, 1, function(x) x-m)) # random effect starting values
  rownames(rmat) <- levels(data$plate)
  colnames(rmat) <- letters[2:5]
  ####################################
  
  # mixed model drm fit
  # mixed model drm fit
  m.1 <- medrc::medrm(
    response ~ dose,
    data = data,#subset(data, strain == strain_name),
    fct = fct,
    # random effects
    #random = b + c + d ~ 1 | plate/sex/strain/mouse, #doesn't work
    # random = b + c + d ~ 1 | mouse , # but this does
    random = b + c + d ~ 1 | mouse / strain / sex / plate, # and this does
    weights = varExp(form = ~ weight_var),
    control = nlme::nlmeControl(
      tolerance = 0.1,
      pnlsTol = 1,
      msMaxIter = 2000
    ),
    # initial values for fixed components
    start = list(fixed = m[c("b", "c", "d", "e")], plate = rmat)
  )

  ### effective dose estimation ED25, ED50, ED75
  # based on the fixed effect estimates
  # conditional on random effects of 0
  # drc::ED(m.1, c(25, 50, 75), interval="tfls") 

  return (m.1)
}

try_mixed_drm_v4 <- function(data, 
                          response_var, 
                          transform, 
                          weight_var = 'dose',
                          fct,
                          strain_name){
  
  # prepare data
  data <- data %>%
    stats::na.omit() %>% 
    dplyr::mutate(sex = as.factor(sex),
          dose = as.numeric(as.character(dose))) %>%
    dplyr::select_(.dots = 
                     list(response = response_var, 
                          weight_var = weight_var,
                          dose = 'dose', 
                          plate = 'plate', 
                          sex = 'sex', 
                          strain = 'strain',
                          mouse = 'mouse')
                   )

  if ('zero_replace' %in% transform){
    print("replacing zero with 0.0001")
    data$response[data$response == 0] <- 0.0001
  }
   if ('log_skew_transform' %in% transform) {
    data$response <- log_skew_transform(data$response)
  } 
    if ('scale_positive' %in% transform){
    # rescale data between 0 and 1
    new_max = abs(min(data$response))+0.001
    print(paste("scaling to 0 and",new_max))
    data$response <- scales::rescale(data$response,to = c(0,new_max),finite=TRUE,na.rm=TRUE)
    } 
  
  # curve specific difference to the parameter average
  check_plate <- medrc::metadrm(
    response ~ dose,
    data = data,
    fct = fct,
    ind = plate,
    struct = "UN"
  )
  
  cmat <- matrix(coefficients(check_plate), ncol=4)
  # fixed effect starting values
  m <- apply(cmat, 2, mean)
  names(m) <- letters[2:5]
  rmat <- t(apply(cmat, 1, function(x) x-m)) # random effect starting values
  rownames(rmat) <- levels(data$plate)
  colnames(rmat) <- letters[2:5]
  ####################################
  
  # mixed model drm fit
  # mixed model drm fit
  m.1 <- medrc::medrm(
    response ~ dose,
    data = data,#subset(data, strain == strain_name),
    fct = fct,
    # random effects
    #random = b + c + d ~ 1 | plate/sex/strain/mouse, #doesn't work
    random = b + c + d ~ 1 | mouse , # but this does
    #random = b + c + d ~ 1 | mouse / strain / sex / plate, # and this does
    weights = varExp(form = ~ weight_var),
    control = nlme::nlmeControl(
      tolerance = 0.1,
      pnlsTol = 1,
      msMaxIter = 2000
    ),
    # initial values for fixed components
    start = list(fixed = m[c("b", "c", "d", "e")], plate = rmat)
  )

  ### effective dose estimation ED25, ED50, ED75
  # based on the fixed effect estimates
  # conditional on random effects of 0
  # drc::ED(m.1, c(25, 50, 75), interval="tfls") 

  return (m.1)
}
```


## Setting up feature instructions

```{r}
start_idx = grep("timepoint", colnames(founders_quantal_collection$all_plates)) + 1
end_idx = grep("number_of_analyzed_fields", colnames(founders_quantal_collection$all_plates)) - 1
founders_quantal_collection$features_df$name_ <- colnames(founders_quantal_collection$all_plates[,start_idx:end_idx])

# example_set <- c("h2axpositive_infocus",
#                        "infocus_intensity_nucleus_alexa488_mean_mean",
#                        "infocus_intensity_cell_hoechst_mean_stdev",
#                        "infocus_cell_roundness_mean",
#                        "infocus_cell_roundness_stdev",
#                        "nuclei_numberofobjects",
#                        "infocus_numberofobjects"
#                        )
```

# Generate DRC curves within nested cluster

```{r}
cl <- suppressWarnings(makeCluster(12, type="SOCK")) # for 12 cores machine

suppressWarnings(doSNOW::registerDoSNOW (cl))

smaller_test <- 

system.time({
    fcts <-  list("LL.4" = LL.4(),"W1.4" = W1.4(),"W2.4" = W2.4())
    cluster_results_df <- foreach (f_ = founders_quantal_collection$features_df$name_[50:75], .combine = 'rbind') %:% 
      foreach (fct_ = fcts, .combine = 'cbind', .inorder=TRUE, .packages = c("drc", "nlme", "medrc","dplyr","stats")) %dopar%  {
        tryCatch(

            expr = {

              m <-try_mixed_drm_v4(founders_quantal_collection$all_plates,
                response_var = f_,
                transform = c('none'),
                weight_var = 'infocus_numberofobjects',
                fct = fct_
                )
              
              ed50 <- drc::ED(m, c(50), interval="tfls", bound=TRUE)[1]
              colname_ <- paste0("ed50_",fct_)
              temp_df_row <- data.frame("name" = f_, "ed50" = ed50)
              colnames(temp_df_row)[2] <- paste0(fct_$name,"_ed50")
              temp_df_row
            },
            error = function(e){
              colname_ <- paste0("ed50_",fct_)
              temp_df_row <- data.frame("name" = f_, "ed50" = NA)
              colnames(temp_df_row)[2] <- paste0(fct_$name,"_ed50")
             temp_df_row
            }
        )
        
      }
    cluster_results_df <- cluster_results_df[, !duplicated(colnames(cluster_results_df), fromLast = FALSE)] 
})
stopCluster(cl)
```

```{r}


# copy_data<-founders_quantal_collection$all_plates
# 
# 
#   # try to get each ED50 per strain out of model
# m.alexa <- suppressWarnings(try_mixed_drm_v3(copy_data, 
#     'infocus_intensity_nucleus_alexa488_mean_mean', 
#     transform = c('log_skew_transform'), 
#     weight_var = 'infocus_numberofobjects',
#     fct = LL.4()
#     ))
# 
# x <- m.alexa
# fct <- x$fct
# yname <- as.character(x$form)[2]
# xname <- as.character(x$form)[3]
# fname <- as.character(x$curveid)[3]
# pform <- x$form
# ndose <- 1000
# mf <- model.frame(pform, data = x$data)
# dr <- seq(min(mf[, 2]), max(mf[, 2]), length = ndose)
# 
# # coefficients for each strain
# cf <- coef(x$fit)
# 
# # this is where the magic happens
# predictions_df <-
#   data.frame(apply(cf, 1, function(para)
#     x$fct$fct(dr, rbind(
#       para
#     ))))
# 
# predictions_stacked <- stack(predictions_df)$values
# 
# pdat <-
#   data.frame(
#     predictions_stacked,
#     dose = rep(dr, times = nrow(cf)),
#     ID = rep(rownames(cf), each = ndose)
#   )
# 
# # average by pdat / strain
# pdat_by_strain <- pdat %>% 
#   separate(ID, c("mouse","strain","sex","plate"), sep = "([./:])") %>%
#    group_by(strain,dose) %>% 
#    summarise_at(vars("predictions_stacked"), mean) %>% 
#   dplyr::select(predictions_stacked, dose, strain) %>% 
#   dplyr::rename(
#     predictions = predictions_stacked,
#     ID = strain
#     ) %>% group_by(ID) %>%
#   filter(row_number()==ceiling(n()/2))
# 
# 
# find_ec50_at_50p <- ndose/2
# 
# p.alexa <- suppressWarnings(mixed_drc_plot_v2(m.alexa, 
#     var = 'alexa',
#     logx = TRUE
# ))
# 
# p.alexa
```

## Save/overwrite RDS

```{r}
# temp_data_storage <- paste0("temp_files/founders_quantal_reduced.RData")
# saveRDS(founders_quantal_collection, temp_data_storage)
```

